### ISSUE TITLE
 Inventory with Japanese client

### ISSUE THREAD

**Issue by cmiscloni** [noelmartinon/updatengine-server#3]
Inventory of Japanese computers don't work as expected, the software inventory is still empty.
Only some informations are up, as Address IP, Model, Make, UUID...

Error in Log file: 

```
INFO:root:Start: 2019-10-25-19:01:58
INFO:root:Inventory built
ERROR:root:Error on send_inventory process
Traceback (most recent call last):
  File "Windows\updatengine-client.py", line 210, in main
  File "Windows\uecommunication.py", line 228, in send_inventory
  File "Windows\uecommunication.py", line 85, in send_xml
  File "urllib2.py", line 429, in open
  File "urllib2.py", line 447, in _open
  File "urllib2.py", line 407, in _call_chain
  File "urllib2.py", line 1241, in https_open
  File "urllib2.py", line 1198, in do_open
URLError: <urlopen error [Errno 11001] getaddrinfo failed>
ERROR:root:Error in main() function
Traceback (most recent call last):
  File "Windows\updatengine-client.py", line 214, in main
SystemExit: 1
INFO:root:*********************************
```

**Comment by noelmartinon** [comment]
What does the command "updatengine-client -v" ? You should see a complete inventory in XML. 
Maybe there is some characters that need to be encoded.

**Comment by cmiscloni** [comment]
The return of this command was:
--> Error when building inventory

**Comment by noelmartinon** [comment]
Is the issue resolved with new 4.0.1 UE-Client ?

**Comment by cmiscloni** [comment]
Unfortunately no.
